### ISSUE TITLE
Show Score and Results

### ISSUE THREAD

**Issue by tgrey2024** [Carlos-n21/UK-Quiz#11]
### User Story
**As a** user completing the quiz,  
**I want to** see my score at the end,  
**So that I can** understand how well I did on the quiz.

**Acceptance Criteria:**
- [x] The score must be calculated based on the user's answers.
- [x] The score must be displayed at the end of the quiz.
- [x] The result page must include an encouraging, congratulatory message based on the score.

**Tasks:**
- [x] Implement score calculation logic using JavaScript.
- [x] Create the result page layout using HTML and CSS.
- [x] Display the user's score on the result page.
- [x] Add congratulatory messages based on different score ranges, including a matching fun image.
- [x] Test the score calculation is correctly done.
- [x] Test that the comments and congratulatory image matches the score.
- [x] Test that scores and comments are displayed corrects.
- [x] Log issues in Project Board
