### ISSUE TITLE
Responsive Design and Wireframes

### ISSUE THREAD

**Issue by tgrey2024** [Carlos-n21/UK-Quiz#13]
A user-friendly interface with consistent styles, clear navigation, and adherence to wireframes/mockups. The layout adapts to different screen sizes using CSS media queries, Flexbox, Grid, and/or Bootstrap without any major errors/loss of functionality.

**Acceptance Criteria:**
- [x] ensure layouts are responsive to different screen sizes, designing mobile first
- [x] ensure UI design match wireframes/mockups
- [x] include wireframes, [am I responsive](https://ui.dev/amiresponsive) etc in README.md
- [x] Ensure use CSS media queries for responsiveness
- [x] Ensure use of Semantic HTML for readability

**Tasks:**
- [x] create wireframes in Balsamiq
- [x] include wireframes in README.md
- [x] Use CSS media queries for responsiveness
- [x] Use Semantic HTML for readability
- [x] test for responsive design in Chrome Dev Tools
- [x] check final layouts against wireframes
- [x] use deployed site on [am I responsive](https://ui.dev/amiresponsive), take screenshot and insert into README.md
