### ISSUE TITLE
Lighthouse Audit

### ISSUE THREAD

**Issue by tgrey2024** [Carlos-n21/UK-Quiz#17]
**Accessibility Criteria:**
- [x] Lighthouse audit should achieve scores of 70+ after fixes to accessibility (aria-labels), image format & size and colour contrast
**Tasks:**
- [x] Deploy site
- [x] run an audit on [Lighthouse](https://www.youtube.com/watch?v=VyaHwvPWuZU)? (eg. correct image format, image compression)
- [x] record scores on mobiles and laptops
- [x] Fix bugs and/or record major issues on Project Board for the team to fix
- [x] Optimise images using Squoosh
- [x] rerun the test on Lighthouse
