### ISSUE TITLE
Mixed Categories

### ISSUE THREAD

**Issue by tgrey2024** [Carlos-n21/UK-Quiz#22]
**User Story:** 
**As a** user visiting the quiz site,  
**I want to** choose to practise questions from different categories,  
**So that I can** assess my knowledge in all different categories.

**Acceptance Criteria:**

- [ ] The homepage must have a clear title.
- [ ] The homepage must include navigation links to a mixed category.
- [ ] A suitable icon should be used so they are easier to understand and navigate.
- [ ] The design must be responsive and look good on different devices (desktop, tablet, mobile).

**Tasks:**
- [ ] Design the homepage layout using HTML and CSS.
- [ ] Add a title, description, and navigation links.
- [ ] Add a category for each question in the question bank.
- [ ] Use JS to retrieve questions from different categories.
- [ ] Implement responsive design using media queries.
- [ ] Test that questions from different categories are included.
